name: Publish NPM Package

on:
    workflow_dispatch:
    release:
        types: [ published ]

jobs:

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint and Format check
        run: bun run lint

  build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: oven-sh/setup-bun@v2
                with:
                    bun-version: 1.2.7
            -   run: bun install
            -   run: bun lint
            -   run: bun bundle
            -   uses: actions/upload-artifact@v4
                with:
                    name: dist
                    path: ./dist

  publish:
        if: github.event_name == 'release'
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v4
                with:
                    registry-url: https://registry.npmjs.org
            -   uses: actions/download-artifact@v4
                with:
                    name: dist
                    path: ./dist
            -   run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}